# -*- coding: utf-8 -*-
"""big data and cloud computing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7UBXvr4s7S0FKbswHvrH3jRaKt8xym8
"""

!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
!tar xf spark-3.5.1-bin-hadoop3.tgz

!pip install -q findspark

!ls -l /content/spark-3.5.1-bin-hadoop3/
!ls -l /content/spark-3.5.1-bin-hadoop3/python/
!ls -l /content/spark-3.5.1-bin-hadoop3/python/lib/

import os
import findspark

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.5.1-bin-hadoop3"

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("MES_Energy_Analysis") \
    .getOrCreate()

df = spark.read.csv(
    "/content/Energy_consumption_dataset.csv",
    header=True,
    inferSchema=True
)

df.show(5)

df.describe().show()

hourly_usage = df.groupBy("Hour") \
                 .avg("EnergyConsumption") \
                 .orderBy("Hour")

hourly_usage.show()

hourly_pd = hourly_usage.toPandas()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(hourly_pd["Hour"],
         hourly_pd["avg(EnergyConsumption)"],
         marker='o')

plt.title("Average Energy Consumption by Hour")
plt.xlabel("Hour")
plt.ylabel("Energy Consumption")
plt.grid(True)
plt.show()

monthly_usage = df.groupBy("Month") \
                  .avg("EnergyConsumption") \
                  .orderBy("Month")

monthly_pd = monthly_usage.toPandas()

plt.figure(figsize=(10,5))
plt.bar(monthly_pd["Month"],
        monthly_pd["avg(EnergyConsumption)"])

plt.title("Average Monthly Energy Consumption")
plt.xlabel("Month")
plt.ylabel("Energy Consumption")
plt.show()

numeric_cols = [
    "Temperature",
    "Humidity",
    "SquareFootage",
    "Occupancy",
    "RenewableEnergy",
    "EnergyConsumption"
]

pandas_df = df.select(numeric_cols).toPandas()

import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(pandas_df.corr(),
            annot=True)

plt.title("Correlation Matrix")
plt.show()

from pyspark.ml.feature import StringIndexer

day_indexer = StringIndexer(
    inputCol="DayOfWeek",
    outputCol="DayOfWeekIndex"
)

holiday_indexer = StringIndexer(
    inputCol="Holiday",
    outputCol="HolidayIndex"
)

hvac_indexer = StringIndexer(
    inputCol="HVACUsage",
    outputCol="HVACIndex"
)

light_indexer = StringIndexer(
    inputCol="LightingUsage",
    outputCol="LightingIndex"
)

from pyspark.ml.feature import VectorAssembler

assembler = VectorAssembler(
    inputCols=[
        "Month",
        "Hour",
        "Temperature",
        "Humidity",
        "SquareFootage",
        "Occupancy",
        "RenewableEnergy",
        "DayOfWeekIndex",
        "HolidayIndex",
        "HVACIndex",
        "LightingIndex"
    ],
    outputCol="features"
)

from pyspark.ml.regression import LinearRegression
from pyspark.ml import Pipeline

pipeline = Pipeline(stages=[
    day_indexer,
    holiday_indexer,
    hvac_indexer,
    light_indexer,
    assembler
])

prepared_data = pipeline.fit(df).transform(df)

train_data, test_data = prepared_data.randomSplit(
    [0.8, 0.2],
    seed=42
)

lr = LinearRegression(
    featuresCol="features",
    labelCol="EnergyConsumption"
)

model = lr.fit(train_data)

predictions = model.transform(test_data)

predictions.select(
    "EnergyConsumption",
    "prediction"
).show(10)

from pyspark.ml.evaluation import RegressionEvaluator

evaluator = RegressionEvaluator(
    labelCol="EnergyConsumption",
    predictionCol="prediction",
    metricName="r2"
)

r2 = evaluator.evaluate(predictions)

print("R2 Score:", r2)

from pyspark.ml.regression import RandomForestRegressor

rf = RandomForestRegressor(
    featuresCol="features",
    labelCol="EnergyConsumption",
    numTrees=100,
    maxDepth=10,
    seed=42
)

rf_model = rf.fit(train_data)

rf_predictions = rf_model.transform(test_data)

rf_predictions.select(
    "EnergyConsumption",
    "prediction"
).show(10)

from pyspark.ml.evaluation import RegressionEvaluator

r2_evaluator = RegressionEvaluator(
    labelCol="EnergyConsumption",
    predictionCol="prediction",
    metricName="r2"
)

r2 = r2_evaluator.evaluate(rf_predictions)

print("Random Forest R² Score:", r2)

# Since it's a scatter plot, we sample the data if it's too large, or plot directly if it fits in memory
# Converting a sample to Pandas for visualization safety
scatter_df = df.select("Temperature", "EnergyConsumption").sample(withReplacement=False, fraction=0.2, seed=42).toPandas()

# Plotting
plt.figure(figsize=(10, 6))
sns.scatterplot(data=scatter_df, x="Temperature", y="EnergyConsumption", alpha=0.5, color="darkorange")
sns.regplot(data=scatter_df, x="Temperature", y="EnergyConsumption", scatter=False, color="red") # Trendline
plt.title("Impact of Temperature on Energy Consumption", fontsize=14)
plt.xlabel("Temperature (°C)", fontsize=12)
plt.ylabel("Energy Consumption (kWh)", fontsize=12)
plt.show()

